/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Paleta Stitch - Material Design 3
        'primary': '#d0c4c0',
        'on-primary': '#362f2c',
        'primary-container': '#1a1412',
        'on-primary-container': '#877d7a',
        'secondary': '#c9c6bf',
        'on-secondary': '#31302b',
        'secondary-container': '#484741',
        'on-secondary-container': '#b8b5ae',
        'tertiary': '#e5c192',
        'on-tertiary': '#422c0a',
        'tertiary-container': '#211200',
        'on-tertiary-container': '#997a51',
        'background': '#18120f',
        'on-background': '#ede0d9',
        'surface': '#1f1813',
        'on-surface': '#ede0d9',
        'surface-variant': '#3b332f',
        'on-surface-variant': '#d1c4c0',
        'outline': '#9a8e8b',
        'outline-variant': '#4e4542',
        'surface-container-lowest': '#130d0a',
        'surface-container-low': '#211a17',
        'surface-container': '#251e1a',
        'surface-container-high': '#302924',
        'surface-container-highest': '#3b332f',
        'surface-dim': '#18120f',
        'surface-bright': '#3f3833',
        'secondary-fixed': '#e6e2da',
        'secondary-fixed-dim': '#c9c6bf',
        'tertiary-fixed': '#ffddb3',
        'tertiary-fixed-dim': '#e5c192',
        'primary-fixed': '#ede0dc',
        'primary-fixed-dim': '#d0c4c0',
      },
      fontFamily: {
        'bodoni': ['Bodoni Moda', 'serif'],
        'manrope': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '84px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '0.05em', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '0.02em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.15em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '500' }],
      },
      spacing: {
        'gutter': '32px',
        'margin-mobile': '24px',
        'margin-desktop': '80px',
        'container-max': '1280px',
        'section-gap': '160px',
      },
      borderRadius: {
        'none': '0px',
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'slide-up': 'slideUp 0.6s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
